### ISSUE TITLE
Might miss a padding?

### ISSUE THREAD

**Issue by CiaoHe** [liuruiyang98/Jittor-MLP#1]
Hi, good to find your implementation!

Here, I wonder whether miss a `padding=patch_size//2`
https://github.com/liuruiyang98/Jittor-MLP/blob/68d587729c05ceb47292cd6829bd32fc107b22ed/models_pytorch/conv_mixer.py#L18

Best

**Comment by liuruiyang98** [comment]
Thanks very much.
Yes, I got careless. It will be fixed as soon as possible.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuruiyang98/Jittor-MLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午4:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liuruiyang98/Jittor-MLP] Might miss a padding? (Issue #1)





 
Hi, good to find your implementation!
 
Here, I wonder whether miss a padding=patch_size//2
 https://github.com/liuruiyang98/Jittor-MLP/blob/68d587729c05ceb47292cd6829bd32fc107b22ed/models_pytorch/conv_mixer.py#L18
 
Best
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
